### PR TITLE
[WIP] Multi dynamodb

### PR DESCRIPTION
**Pull request by jakepruitt**
Created to implement multiple-master replication. Work in progress.

### CODE REVIEW

**Comment by rclark** [comment]
To me the logic becomes much simpler when you use conditional writes. It boils down to:
- you get an OldImage and a NewImage
- you put the NewImage to the other table, but conditionally, rejecting the put if the record's state is not 100% === your OldImage
- in the very first pass, if the put goes through, we're all good, and if not, we just log that there's conflicts (we can think about solving conflicts next)

So I had forgotten that we don't use dyno in the replication, which means I needed to go back and study up on conditional writes in the real aws-js-sdk. Here's a gist with a really simple example outlined on how to conditionally write: https://gist.github.com/rclark/8528a925a37294b5b5fc

**Comment by jakepruitt** [comment]
@rclark I'm not pleased with the amount of logic that still exists in the code. Even with conditional writes, we still need logic in place for handling conflicts.

A lot of this logic requires a read from the destination table to check if the conflict occurred because the modification has already taken place. My initial thought was to perform another conditional write with the condition being that the existing object equals the new object, but realized that if that succeeded, it would result in an infinite ping-pong loop. My other thought was to add an attribute called `_replicated` to objects when the modification was done by the replicator, and we could ignore any boomerang events by simply ignoring anything with the `_replicated` flag. But then I realized that future updates to those objects would not be persisted.

Thus, our only solution is to read the target table in the event of a conflict, if it equals what we want already, do nothing. If it is in conflict, perform the same action again only without the conditional check. The other possible solution is to use a "puppet-master bucket" or "puppet-master table" like we discussed that acted as the check before writes took place. At the moment, *most* replication events are done without reads from Dynamo, but boomerang events and conflicts will require reads.

I still fear the situation of competing updates on the two masters swapping each other in an infinite loop. Imagine one table getting the "set to red" update and the other "set to white" update. After replication, the "last updated wins" model will result in flip-flopped colors for each table. Those changes will boomerang back and swap the colors again. This loop never exits. The only way to solve it is the puppet master, I think.

What I need at the beginning of this week are two things:
- Understanding of comma-separated CloudFormation parameters and using them to create permissions.
- Hear your opinion of S3 puppet-master bucket based on the versioned backup work you are doing.

**Comment by rclark** [comment]
Let's break this up into the three things that need to happen:
- we need to push writes from one table onto another (yay! easy!)
- we need to identify when conflicting writes are performed (yay! conditional writes tell us!)
- we need to manage the conflict scenario (?!@?!#)

We're 2/3 of the way there! Before we dive deep into any automated conflict management, we should build it so that we can manage conflicts manually. This will better inform how we build an automated system. Let's think about _what information we can gather automatically_ that will be required in order to resolve conflicts. Let's see what it means to resolve them manually and learn how we can effectively automate that process?

One of the things that strikes me is that once you identify a conflict, you need to know the history of changes made to the conflict record in both tables since they diverged -- there could be many, many conflicting versions hiding. Last weekend I sketched out a function to write every change to an object on S3: https://github.com/mapbox/dynamodb-replicator/pull/32. If this were in a versioned bucket, and you had one for each table, you could trace versions back through history until you find the common origin, and every change to either table after that point is a conflict version. What if one Lambda function simply tried to make conditional writes, and when one failed, invoked _another_ function that found all the conflict versions and listed them for us / notified us of the conflict?

**Comment by rclark** [comment]
I forgot about ping-pong and have to think it through so bear with me...

So OldImage = existing record is a problem because 
- Table A writes record from v1 to v2
- Replication replays v1 to v2 onto table B
- Replication replay's _B's change back onto Table A_, which fails a conditional write and looks like a conflict even though it isn't.

I think you're right on about the easiest solution:
- perform a conditional write checking that `target === OldImage`
- if that fails, perform a strongly-consistent read on the target table, `assert.deepEqual(target, NewImage)`. If that passes then exit (you've got a ping-ponged write coming at you), if it does not pass then move on to conflict management (see above)

**Comment by jakepruitt** [comment]
> we need to manage the conflict scenario (?!@?!#)

After talking with @miccolis, @rclark and @yhahn about the conflict scenario, and spending some time thinking about it carefully, I just want to braindump my ideas for how we will handle conflict in a multiple master situation.

First of all, let's list the causes of the conflict scenario:

1. Writes happen at the same time to two tables (not very common, but possible)
2. Partial failure within the replication system (very possible, and almost inevitable)

The algorithm that we choose **must** be able to provide a predictable state when either of these events occur. An algorithm **fails** if it either results in a major loss of data or an unstable state of the databases.

## Last-lambda-call-wins Cannot Handle Simultaneous Updates

Currently, we have implemented a simple system that uses "Last-lambda-call-wins". Here is an outline:

1. An item is updated in the source table.
2. The update triggers the Lambda Function, passing it the old state and the new state
3. If the item in the target table equals the old state, update the item in the target table to the new state
4. If the item in the target table equals the new state, nothing needs to be done
5. If the item in the target table does not equal the new state or the old state, this means the items are in conflict, and the item in the target table is updated to the new state (since this was the "last write").

This algorithm suffers from an implementation detail of Lambda Function replication. Every replication event *also* triggers the lambda function, sending the update *back* to the source table. That is why step 4 above is necessary, and why the condition in step 5 could lead to imbalance.

Imagine both the source and target get updates to the same item at the same time. The way Lambda works, one of them will be triggered first:

```
source -~~~~~+++~~~~~++
         \  / \/ \  / \
          \/  /\  \/      ....  and so on, back and forth
          /\ /  \ /\ /
target --+++~~~~~+++~~~
```

When the `~` update from the source table arrives at the target table and finds the state to be `+`, it overwrites the existing state (last write wins). The `~` update is then passed back to the source table, which has already been overwritten by the `+` update. It finds the states in conflict again, and continues to flip flop between the two states without ever reaching a stable situation.

In the situation of a partial failure, things could become very chaotic. Pretty much any situation where the target doesn't equal the old image or the new image sends the table into this imploding state.

## Adding time to the equation

One way to solve this problem is to not base the "Last write" order on the arbitrary invocation order of the lambda function, but instead attach a timestamp to each record indicating when it was last changed. Then compare these timestamps in the event of a conflict. This prevents the situation above from ever happening, because either the `~` event or `+` event occured first, and the loop would never even begin.

While clocks can be [somewhat dubious](http://research.microsoft.com/en-us/um/people/lamport/pubs/time-clocks.pdf) when used in a distributed system, timestamps would also provide a way for the repair script to determine a winner if it finds a conflict. Otherwise, finding a conflict in the two tables would leave the repair script at a loss, and the databases would be divergent until someone could come in and manually fix it. "Last-lambda-write" would not give the repair script any idea as to which record should win, unless we specified some arbitrary determination, such as always prefer `us-east-1`.

## Removing time from the equation

If it is technically impossible or unsavory to be adding timestamps to every write operation in dynamo, we could resolve conflicts based on a canonical versioned history of updates. The versioned history could be checked to see if the conflicting target state is older than the OldImage (in which case we can update) or newer than the OldImage (in which case, things are truly conflicted, and we can use the history to determine which should win, such as whichever item has had the most updates since a common ancestor). This method involves much more heavy-handed logic than timestamp comparison, and adds another potential point of failure for the system. But we would have a guaruntee that conflicts would resolve, and it would provide a history that could be used in handling the conflicts during the repair loop or during manual resolving. I like to think of this as a git-based approach, which may or may not be very useful when dealing with databases.

## Other methods used in the wild

Here are some other ways people are solving this problem in the wild.

* Adding revisions to all items, which act as both a vector clock and a history (couch)
* Using more than two databases and resolving things based on majority vote (dynamo-behind-the-curtain, paxos)
* Preventing conflicts by writing to all tables on a write request (SQL)

These options are open, but I figured the options already outlined seemed simpler.

**Comment by miccolis** [comment]
Some thoughts:

* Totally agree "Last-lambda-call-wins" is a non-strategy, but it's not clear to me that we ever talked about considering it. right?
* "Greatest time stamp wins" is what I assumed we'd been pursuing and as you describe it only has the problem of dealing with a situation where different records have the same time stamp. (At our scale this is inevitable.) You mention using "some arbitrary determination" but seem to dismiss it. Why? I think this is a great solution.
* I'd be wary of the idea of "canonical versioned history of updates." I'm not sure what this even would mean in a master-master scenario. If it's even possible, going for this is promising a lot more than we need. We need consistent state, not so much a git history. Is there anyway simple consistency wouldn't work for us?

**Comment by rclark** [comment]
The timestamp / rev idea is really challenging for DynamoDB, because it places a client-side burden that you write some sort of version id every time you make a change to a record. We have been doing this with kinesis writes, but it is so gross, I'm very excited to remove it, and I have seen snakes and gila monsters crying about it while I'm hiking on the weekends.

It gets way more complex, but maybe we need a replication master of sorts that can keep track of history and replication state for us. All the table's dynamo streams would point at that replication master, who would then push the appropriate changes out to the other tables in the group. My mind isn't totally clear yet on what exactly this would look like, but just throwing it out onto the pile of ideas.

btw I think that in a multi-master scenario running a repair loop will only muddy the waters. We would adjust the script to log discrepancies without repairing them, turning it into basically the drift alarm we currently have on couch.

**Comment by willwhite** [comment]
> "Greatest time stamp wins" is what I assumed we'd been pursuing

I assumed the same. I think it makes sense to follow the example set by [DynamoDB CRR library](https://github.com/awslabs/dynamodb-cross-region-library/blob/master/library/DESIGN.md).

Also, it sounds like we have some feature requests for the DynamoDB team that could make this easier:

- timestamp for each stream record (surprised they didn't add this for their own library)
- something on the stream record that indicates the source of an update (so you can determine a update that came from the application vs one that came from the replicator)

The other thing we need to think about is deletes - multi-master might require us to switch to tombstones that contain `timestamp`.

**Comment by rclark** [comment]
I'm not convinced that the CRR lib is a good model to follow. Most of the requirements that you linked to make me gag a little bit and specifically, disallowing BatchWriteItem requests is totally not acceptable.

**Comment by willwhite** [comment]
Based on my understanding of other replication systems (like couchdb) the
requirements feel par for the course - they are just a little more raw
because DynamoDB doesn't have all of the features we need to hide away the
internals.

I noticed that BatchWriteItem was disallowed but it's not clear to me why
this is the case and if this is a hard requirement.

Stepping back, I think we can gather our options (I would like to better
understand the alternatives because so far it appears to introduce a big
single point of failure), communicate our feedback to the Dynamo team,
and table the MM discussion while we take some steps to workaround single
master replication lag that we discussed.

On Friday, July 3, 2015, Ryan Clark <notifications@github.com> wrote:

> I'm not convinced that the CRR lib is a good model to follow. Most of the
> requirements that you linked to make me gag a little bit and specifically,
> disallowing BatchWriteItem requests is totally not acceptable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/dynamodb-replicator/pull/31#issuecomment-118391581>
> .
>


-- 
202-250-3633 | will@mapbox.com | @willwhitedc

**Comment by jakepruitt** [comment]
We have global tables in dynamodb now, with multi-master replication built in. Closing this.

**Pull request closed without merging**
